const CLOSE_WINDOW_IPC = 'CLOSE_WINDOW_IPC'
const MINIMIZE_WINDOW_IPC = 'MINIMIZE_WINDOW_IPC'
const MAXIMIZE_WINDOW_IPC = 'MAXIMIZE_WINDOW_IPC'

module.exports = {
    CLOSE_WINDOW_IPC,
    MINIMIZE_WINDOW_IPC,
    MAXIMIZE_WINDOW_IPC
}